# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hello.proto

require 'google/protobuf'


descriptor_data = "\n\x0bhello.proto\x12\x05hello\"\x1b\n\x0cHelloRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x1c\n\rHelloResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"!\n\x12HelloStreamRequest\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\"\n\x13HelloStreamResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\x9d\x02\n\x05hello\x12\x34\n\x05Hello\x12\x13.hello.HelloRequest\x1a\x14.hello.HelloResponse\"\x00\x12H\n\x11HelloServerStream\x12\x13.hello.HelloRequest\x1a\x1a.hello.HelloStreamResponse\"\x00\x30\x01\x12H\n\x11HelloClientStream\x12\x19.hello.HelloStreamRequest\x1a\x14.hello.HelloResponse\"\x00(\x01\x12J\n\x0bHelloStream\x12\x19.hello.HelloStreamRequest\x1a\x1a.hello.HelloStreamResponse\"\x00(\x01\x30\x01\x62\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Hello
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloRequest").msgclass
  HelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloResponse").msgclass
  HelloStreamRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloStreamRequest").msgclass
  HelloStreamResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("hello.HelloStreamResponse").msgclass
end
